//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timbervale
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATTLE_MOVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BATTLE_MOVE()
        {
            this.ENEMY_MOVES = new HashSet<ENEMY_MOVES>();
            this.PLAYER_MOVES = new HashSet<PLAYER_MOVES>();
        }
    
        public int moveID { get; set; }
        public string moveName { get; set; }
        public string moveDescription { get; set; }
        public Nullable<int> movePower { get; set; }
        public Nullable<int> cooldown { get; set; }
        public string compatibility { get; set; }
        public Nullable<bool> canBind { get; set; }
        public Nullable<bool> canBleed { get; set; }
        public Nullable<bool> canPoison { get; set; }
        public Nullable<bool> canParalyze { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENEMY_MOVES> ENEMY_MOVES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAYER_MOVES> PLAYER_MOVES { get; set; }
    }
}
