//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timbervale
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENEMY_MOVES
    {
        public int enemyMovesID { get; set; }
        public int moveID { get; set; }
        public int enemyID { get; set; }
    
        public virtual BATTLE_MOVE BATTLE_MOVE { get; set; }
        public virtual ENEMY ENEMY { get; set; }
    }
}
