//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timbervale
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPPED_ITEMS
    {
        public int equippedItemsID { get; set; }
        public int playerID { get; set; }
        public int enemyID { get; set; }
        public int itemID { get; set; }
    
        public virtual ENEMY ENEMY { get; set; }
        public virtual ITEM ITEM { get; set; }
        public virtual PLAYER PLAYER { get; set; }
    }
}
